# Generated by Django 5.2.1 on 2025-05-25 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_published', models.DateField()),
                ('image', models.ImageField(upload_to='real_estates/')),
                ('characteristics', models.CharField(blank=True, default='', max_length=260, null=True)),
                ('is_reserved', models.BooleanField()),
                ('is_sold', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=15)),
                ('profile_link', models.URLField()),
                ('total_sales', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examTask2App.characteristic')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examTask2App.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examTask2App.agent')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examTask2App.realestate')),
            ],
        ),
    ]
