# Generated by Django 5.2.1 on 2025-05-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CakeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
